import numpy
n,m = map(int,input().strip().split(' '))
arr1 = numpy.array([input().strip().split(' ') for _ in range(n)],int)
arr2 = numpy.array([input().strip().split(' ') for _ in range(n)],int)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1//arr2)
print(arr1%arr2)
print(arr1**arr2)